import os
import re
import math
from pathlib import Path
from typing import Optional, Dict, Tuple, List

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# FINAL COMPARISON PANELS: FAPI vs FAPI-TEMPO
# ------------------------------------------------------------
# Uses:
#   1) Existing compare outputs (rate/Nt CSVs)
#   2) Event CSVs (kinetics_tau0p3_events*.csv)
#   3) frame_kinetics.csv for BOTH datasets -> global growth proxy
#
# Outputs go to:
#   ...\final_panels_plus_growth\
# ============================================================


# -------------------------
# PATHS (EDIT ONLY IF NEEDED)
# -------------------------
# Compare output folder already generated by compare_fapi_vs_fapi_tempo.py
COMPARE_OUT_DIR = Path(
    r"F:\Sandy_data\AI segemetation work\Sts_grain morphology_ML\Kinetics\out\stable_nucleation_compare_final\compare_FAPI_vs_FAPI_TEMPO"
)

# FAPI matched kinetics folder (from retrack-based reconstruction)
FAPI_MATCHED_DIR = Path(
    r"F:\Sandy_data\AI segemetation work\Sts_grain morphology_ML\Kinetics\out\FAPI\retrack_cuda_vith\matched_kinetics_for_compare"
)

# FAPI-TEMPO stable kinetics folder (artifact-filtered tau0p3 events etc.)
TEMPO_STABLE_DIR = Path(
    r"F:\Sandy_data\AI segemetation work\Sts_grain morphology_ML\Kinetics\stable_v15_out_overlap03_poly_pad400"
)

# Frame-level segmentation kinetics (global growth proxy source)
FAPI_FRAME_KIN_CSV = Path(
    r"F:\Sandy_data\AI segemetation work\Sts_grain morphology_ML\Kinetics\sam_cuda_vith_clean\FAPI\frame_kinetics.csv"
)
TEMPO_FRAME_KIN_CSV = Path(
    r"F:\Sandy_data\AI segemetation work\Sts_grain morphology_ML\Kinetics\sam_cuda_vith_clean\FAPI_TEMPO\frame_kinetics.csv"
)

# Output subfolder
OUT_DIR = COMPARE_OUT_DIR / "final_panels_plus_growth"

# -------------------------
# OPTIONAL PHYSICAL SCALE
# -------------------------
# Set micrometers per pixel if known (example: 0.108)
PX_TO_UM: Optional[float] = None

# -------------------------
# PLOTTING PARAMETERS
# -------------------------
EVENT_HIST_BIN_MS = 20.0   # for event hist / event-rate hist
SAVE_DPI = 300

# If tau sweep files exist, script will auto-plot robustness panel using these tags:
TAU_SWEEP_TAGS = ["0p2", "0p3", "0p4"]


# ============================================================
# Helpers
# ============================================================

def ensure_exists(path: Path, label: str = "file") -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing {label}: {path}")


def read_csv(path: Path, label: str = "CSV") -> pd.DataFrame:
    ensure_exists(path, label)
    return pd.read_csv(path)


def safe_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def mkdir_p(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def savefig(path: Path) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=SAVE_DPI)
    plt.close()


# ============================================================
# Load compare curves (already generated)
# ============================================================

def load_rate_curve(path: Path, dataset_name: str) -> pd.DataFrame:
    df = read_csv(path, f"rate curve ({dataset_name})").copy()

    # Flexible column handling
    if "t_center_s" not in df.columns:
        if "t_s" in df.columns:
            df["t_center_s"] = safe_numeric(df["t_s"])
        elif "t_center_ms" in df.columns:
            df["t_center_s"] = safe_numeric(df["t_center_ms"]) / 1000.0

    if "dNdt_per_s" not in df.columns:
        if "rate" in df.columns:
            df["dNdt_per_s"] = safe_numeric(df["rate"])

    req = ["t_center_s", "dNdt_per_s"]
    missing = [c for c in req if c not in df.columns]
    if missing:
        raise ValueError(f"Rate curve missing columns {missing} in {path}")

    df["t_center_s"] = safe_numeric(df["t_center_s"])
    df["dNdt_per_s"] = safe_numeric(df["dNdt_per_s"])
    df = df.dropna(subset=["t_center_s", "dNdt_per_s"]).sort_values("t_center_s").reset_index(drop=True)
    df["dataset"] = dataset_name
    return df


def load_Nt_curve(path: Path, dataset_name: str) -> pd.DataFrame:
    df = read_csv(path, f"Nt curve ({dataset_name})").copy()

    if "t_s" not in df.columns:
        if "t_ms" in df.columns:
            df["t_s"] = safe_numeric(df["t_ms"]) / 1000.0

    if "N" not in df.columns:
        raise ValueError(f"Nt curve missing 'N' column in {path}")

    df["t_s"] = safe_numeric(df["t_s"])
    df["N"] = safe_numeric(df["N"])
    df = df.dropna(subset=["t_s", "N"]).sort_values("t_s").reset_index(drop=True)
    df["dataset"] = dataset_name
    return df


# ============================================================
# Event files (tau0p3 events)
# ============================================================

def load_events_csv(path: Path, dataset_name: str) -> pd.DataFrame:
    df = read_csv(path, f"events ({dataset_name})").copy()

    # Support t_s or t_ms
    if "t_s" not in df.columns:
        if "t_ms" in df.columns:
            df["t_s"] = safe_numeric(df["t_ms"]) / 1000.0

    if "t_ms" not in df.columns:
        if "t_s" in df.columns:
            df["t_ms"] = safe_numeric(df["t_s"]) * 1000.0

    req = ["t_s", "t_ms"]
    missing = [c for c in req if c not in df.columns]
    if missing:
        raise ValueError(f"Events file missing columns {missing} in {path}")

    df["t_s"] = safe_numeric(df["t_s"])
    df["t_ms"] = safe_numeric(df["t_ms"])
    df = df.dropna(subset=["t_s", "t_ms"]).sort_values("t_s").reset_index(drop=True)
    df["dataset"] = dataset_name
    return df


# ============================================================
# Global growth proxy from frame_kinetics.csv
# ============================================================

_FRAME_TIME_RE = re.compile(r"_t([0-9]+(?:\.[0-9]+)?)ms", re.IGNORECASE)


def _extract_time_ms_from_frame_id(frame_id_val) -> float:
    if pd.isna(frame_id_val):
        return np.nan
    m = _FRAME_TIME_RE.search(str(frame_id_val))
    return float(m.group(1)) if m else np.nan


def load_global_frame_growth(frame_kin_csv: Path, dataset_name: str) -> Optional[pd.DataFrame]:
    """
    Builds a global growth proxy from frame_kinetics.csv:
      t_s, t_ms, R_px, dRdt_px_per_s (+ optional um columns)
    Uses largest object per frame (by area or R_px) as "global transformed region".
    """
    if not frame_kin_csv.exists():
        print(f"[WARN] Missing frame_kinetics for {dataset_name}: {frame_kin_csv}")
        return None

    df = pd.read_csv(frame_kin_csv)
    if df.empty:
        print(f"[WARN] Empty frame_kinetics for {dataset_name}: {frame_kin_csv}")
        return None

    # Time handling:
    # In your files, time_ms is often constant 0.0, so parse from frame_id.
    use_time_ms = None
    if "time_ms" in df.columns:
        tms = safe_numeric(df["time_ms"])
        if tms.notna().sum() > 0 and (tms.max() - tms.min()) > 1e-12:
            use_time_ms = tms

    if use_time_ms is None:
        if "frame_id" not in df.columns:
            print(f"[WARN] No usable time column in {frame_kin_csv}")
            return None
        use_time_ms = df["frame_id"].map(_extract_time_ms_from_frame_id)

    df["t_ms_use"] = safe_numeric(use_time_ms)
    df["t_s"] = df["t_ms_use"] / 1000.0

    # Radius handling
    if "R_px" in df.columns:
        df["R_px_use"] = safe_numeric(df["R_px"])
    elif "area_px" in df.columns:
        area = safe_numeric(df["area_px"])
        df["R_px_use"] = np.sqrt(area / np.pi)
    else:
        print(f"[WARN] No R_px/area_px in {frame_kin_csv}")
        return None

    # Largest object per frame as global proxy
    if "area_px" in df.columns:
        df["area_px_num"] = safe_numeric(df["area_px"])
        df = df.sort_values(["t_s", "area_px_num"], ascending=[True, False])
    else:
        df = df.sort_values(["t_s", "R_px_use"], ascending=[True, False])

    g = (
        df.dropna(subset=["t_s", "R_px_use"])
          .groupby("t_s", as_index=False)
          .first()
          .copy()
    )

    if g.empty:
        print(f"[WARN] No valid rows after grouping for {dataset_name}")
        return None

    # Keep clean columns
    out = pd.DataFrame({
        "t_s": safe_numeric(g["t_s"]),
        "t_ms": safe_numeric(g["t_s"]) * 1000.0,
        "R_px": safe_numeric(g["R_px_use"]),
    }).dropna().sort_values("t_s").reset_index(drop=True)

    if len(out) < 3:
        print(f"[WARN] Too few points for growth derivative ({dataset_name})")
        return None

    # Numerical derivative dR/dt [px/s]
    t = out["t_s"].to_numpy(dtype=float)
    r = out["R_px"].to_numpy(dtype=float)
    # gradient handles nonuniform spacing
    dRdt = np.gradient(r, t)
    out["dRdt_px_per_s"] = dRdt
    out["dataset"] = dataset_name
    out["growth_source"] = str(frame_kin_csv)

    # Optional physical units
    if PX_TO_UM is not None:
        out["R_um"] = out["R_px"] * PX_TO_UM
        out["dRdt_um_per_s"] = out["dRdt_px_per_s"] * PX_TO_UM

    return out


# ============================================================
# Metrics / summaries
# ============================================================

def first_time_at_fraction(nt: pd.DataFrame, frac: float) -> float:
    if nt.empty:
        return np.nan
    n_final = int(nt["N"].iloc[-1])
    target = math.ceil(frac * n_final)
    rows = nt.loc[nt["N"] >= target]
    return float(rows["t_s"].iloc[0]) if not rows.empty else np.nan


def summarize_dataset(nt_df: pd.DataFrame, rate_df: pd.DataFrame, events_df: pd.DataFrame,
                      growth_df: Optional[pd.DataFrame]) -> Dict[str, float]:
    out = {}

    if not nt_df.empty:
        out["N_final"] = int(nt_df["N"].iloc[-1])
        out["onset_s"] = float(nt_df["t_s"].iloc[0])
        out["t_last_s"] = float(nt_df["t_s"].iloc[-1])
        out["t10_s"] = first_time_at_fraction(nt_df, 0.10)
        out["t50_s"] = first_time_at_fraction(nt_df, 0.50)
        out["t90_s"] = first_time_at_fraction(nt_df, 0.90)
    else:
        out.update({k: np.nan for k in ["N_final", "onset_s", "t_last_s", "t10_s", "t50_s", "t90_s"]})

    if not rate_df.empty:
        idx = rate_df["dNdt_per_s"].idxmax()
        out["peak_dNdt_per_s"] = float(rate_df.loc[idx, "dNdt_per_s"])
        out["t_peak_dNdt_s"] = float(rate_df.loc[idx, "t_center_s"])
    else:
        out["peak_dNdt_per_s"] = np.nan
        out["t_peak_dNdt_s"] = np.nan

    out["n_events_rows"] = int(len(events_df))

    if growth_df is not None and not growth_df.empty:
        idx2 = growth_df["dRdt_px_per_s"].abs().idxmax()
        out["R_eq_start_px"] = float(growth_df["R_px"].iloc[0])
        out["R_eq_end_px"] = float(growth_df["R_px"].iloc[-1])
        out["peak_abs_dReqdt_px_per_s"] = float(abs(growth_df.loc[idx2, "dRdt_px_per_s"]))
        out["t_peak_abs_dReqdt_s"] = float(growth_df.loc[idx2, "t_s"])
        if "R_um" in growth_df.columns:
            out["R_eq_start_um"] = float(growth_df["R_um"].iloc[0])
            out["R_eq_end_um"] = float(growth_df["R_um"].iloc[-1])
            out["peak_abs_dReqdt_um_per_s"] = float(abs(growth_df.loc[idx2, "dRdt_um_per_s"]))
    else:
        out["R_eq_start_px"] = np.nan
        out["R_eq_end_px"] = np.nan
        out["peak_abs_dReqdt_px_per_s"] = np.nan
        out["t_peak_abs_dReqdt_s"] = np.nan
        out["R_eq_start_um"] = np.nan
        out["R_eq_end_um"] = np.nan
        out["peak_abs_dReqdt_um_per_s"] = np.nan

    return out


# ============================================================
# Plotters
# ============================================================

def plot_dn_dt(rate_fapi: pd.DataFrame, rate_tempo: pd.DataFrame, out_dir: Path) -> None:
    plt.figure(figsize=(10, 6))
    plt.plot(rate_fapi["t_center_s"] * 1000.0, rate_fapi["dNdt_per_s"], marker="o", label=f"FAPI (n={int(rate_fapi['dNdt_per_s'].sum()*0+len(read_csv(FAPI_MATCHED_DIR / 'kinetics_tau0p3_events_FAPI.csv', 'FAPI events')) )})")
    plt.plot(rate_tempo["t_center_s"] * 1000.0, rate_tempo["dNdt_per_s"], marker="o", label=f"FAPI-TEMPO (n={int(len(read_csv(TEMPO_STABLE_DIR / 'kinetics_tau0p3_events.csv', 'TEMPO events')) )})")
    plt.xlabel("time (ms)")
    plt.ylabel("dN/dt (1/s)")
    plt.title("Nucleation rate dN/dt\nFAPI vs FAPI-TEMPO")
    plt.legend()
    savefig(out_dir / "compare_dn_dt_FAPI_vs_FAPI-TEMPO.png")


def plot_Nt(nt_fapi: pd.DataFrame, nt_tempo: pd.DataFrame, out_dir: Path) -> None:
    plt.figure(figsize=(10, 6))
    plt.step(nt_fapi["t_s"] * 1000.0, nt_fapi["N"], where="post", label=f"FAPI (n={int(nt_fapi['N'].iloc[-1])})")
    plt.step(nt_tempo["t_s"] * 1000.0, nt_tempo["N"], where="post", label=f"FAPI-TEMPO (n={int(nt_tempo['N'].iloc[-1])})")
    plt.xlabel("time (ms)")
    plt.ylabel("cumulative stable nuclei N(t)")
    plt.title("Cumulative nucleation N(t)\nFAPI vs FAPI-TEMPO")
    plt.legend()
    savefig(out_dir / "compare_Nt_FAPI_vs_FAPI-TEMPO.png")


def plot_Nt_normalized(nt_fapi: pd.DataFrame, nt_tempo: pd.DataFrame, out_dir: Path) -> None:
    plt.figure(figsize=(10, 6))
    for nt, name in [(nt_fapi, "FAPI"), (nt_tempo, "FAPI-TEMPO")]:
        nfinal = float(nt["N"].iloc[-1]) if len(nt) else np.nan
        y = nt["N"] / nfinal if nfinal > 0 else nt["N"] * np.nan
        plt.step(nt["t_s"] * 1000.0, y, where="post", label=f"{name} (n={int(nfinal)})")
    plt.xlabel("time (ms)")
    plt.ylabel("N(t) / Nfinal")
    plt.title("Normalized cumulative nucleation")
    plt.legend()
    savefig(out_dir / "compare_Nt_normalized_FAPI_vs_FAPI-TEMPO.png")


def _make_event_hist(events_ms: np.ndarray, bin_ms: float) -> Tuple[np.ndarray, np.ndarray]:
    if len(events_ms) == 0:
        return np.array([]), np.array([])
    tmin = 0.0
    tmax = float(np.nanmax(events_ms))
    edges = np.arange(tmin, tmax + bin_ms + 1e-9, bin_ms)
    if len(edges) < 2:
        edges = np.array([0.0, bin_ms])
    counts, edges = np.histogram(events_ms, bins=edges)
    centers = 0.5 * (edges[:-1] + edges[1:])
    return centers, counts


def plot_event_hist(events_fapi: pd.DataFrame, events_tempo: pd.DataFrame, out_dir: Path, bin_ms: float) -> None:
    c1, n1 = _make_event_hist(events_fapi["t_ms"].to_numpy(dtype=float), bin_ms)
    c2, n2 = _make_event_hist(events_tempo["t_ms"].to_numpy(dtype=float), bin_ms)

    plt.figure(figsize=(10, 6))
    if len(c1):
        plt.plot(c1, n1, marker="o", label=f"FAPI (n={len(events_fapi)})")
    if len(c2):
        plt.plot(c2, n2, marker="o", label=f"FAPI-TEMPO (n={len(events_tempo)})")
    plt.xlabel("time (ms)")
    plt.ylabel(f"events / {int(bin_ms)} ms bin")
    plt.title(f"Nucleation event histogram (bin = {int(bin_ms)} ms)")
    plt.legend()
    savefig(out_dir / "compare_event_hist_FAPI_vs_FAPI-TEMPO.png")


def plot_event_hist_rate(events_fapi: pd.DataFrame, events_tempo: pd.DataFrame, out_dir: Path, bin_ms: float) -> None:
    c1, n1 = _make_event_hist(events_fapi["t_ms"].to_numpy(dtype=float), bin_ms)
    c2, n2 = _make_event_hist(events_tempo["t_ms"].to_numpy(dtype=float), bin_ms)

    scale = 1000.0 / bin_ms  # convert counts/bin to counts/s
    plt.figure(figsize=(10, 6))
    if len(c1):
        plt.plot(c1, n1 * scale, marker="o", label=f"FAPI (n={len(events_fapi)})")
    if len(c2):
        plt.plot(c2, n2 * scale, marker="o", label=f"FAPI-TEMPO (n={len(events_tempo)})")
    plt.xlabel("time (ms)")
    plt.ylabel("event histogram rate (1/s)")
    plt.title(f"Nucleation event histogram rate (bin = {int(bin_ms)} ms)")
    plt.legend()
    savefig(out_dir / "compare_event_hist_rate_FAPI_vs_FAPI-TEMPO.png")


def plot_tau_robustness_panel(compare_dir: Path, out_dir: Path) -> None:
    """
    Best-effort tau robustness panel from kinetics_tau{tag}_Nt.csv in FAPI-TEMPO stable folder.
    FAPI is fixed (tau0p3 matched reconstruction).
    """
    # FAPI fixed
    fapi_nt_path = FAPI_MATCHED_DIR / "kinetics_tau0p3_Nt.csv"
    if not fapi_nt_path.exists():
        print("[WARN] FAPI tau0p3 Nt not found; skipping tau robustness panel.")
        return
    fapi_nt = load_Nt_curve(fapi_nt_path, "FAPI")

    curves = []
    for tag in TAU_SWEEP_TAGS:
        p = TEMPO_STABLE_DIR / f"kinetics_tau{tag}_Nt.csv"
        if p.exists():
            curves.append((tag, load_Nt_curve(p, f"FAPI-TEMPO tau={tag.replace('p','.')}")))

    if not curves:
        print("[WARN] No FAPI-TEMPO tau sweep Nt files found; skipping tau robustness panel.")
        return

    plt.figure(figsize=(10, 6))
    plt.step(fapi_nt["t_s"] * 1000.0, fapi_nt["N"], where="post", linewidth=2.5, label=f"FAPI fixed (tau=0.3, n={int(fapi_nt['N'].iloc[-1])})")
    for tag, nt in curves:
        plt.step(nt["t_s"] * 1000.0, nt["N"], where="post", label=f"FAPI-TEMPO tau={tag.replace('p','.')} (n={int(nt['N'].iloc[-1])})")
    plt.xlabel("time (ms)")
    plt.ylabel("N(t)")
    plt.title("Tau robustness panel (FAPI fixed vs FAPI-TEMPO tau sweep)")
    plt.legend()
    savefig(out_dir / "tau_robustness_panel_FAPI_fixed_vs_TEMPO_tau_sweep.png")


def plot_growth_proxy(g_fapi: Optional[pd.DataFrame], g_tempo: Optional[pd.DataFrame], out_dir: Path) -> None:
    if g_fapi is None or g_tempo is None:
        print("[WARN] No usable growth sources found for either dataset. Growth plots skipped.")
        return

    # ----- R_eq in px -----
    plt.figure(figsize=(10, 6))
    plt.plot(g_fapi["t_ms"], g_fapi["R_px"], label="FAPI")
    plt.plot(g_tempo["t_ms"], g_tempo["R_px"], label="FAPI-TEMPO")
    plt.xlabel("time (ms)")
    plt.ylabel(r"Global equivalent radius $R_{eq}$ (px)")
    plt.title("Global growth proxy from frame_kinetics (largest object / frame)")
    plt.legend()
    savefig(out_dir / "compare_global_Req_px_vs_t_FAPI_vs_FAPI-TEMPO.png")

    # ----- dR/dt in px/s -----
    plt.figure(figsize=(10, 6))
    plt.plot(g_fapi["t_ms"], g_fapi["dRdt_px_per_s"], label="FAPI")
    plt.plot(g_tempo["t_ms"], g_tempo["dRdt_px_per_s"], label="FAPI-TEMPO")
    plt.xlabel("time (ms)")
    plt.ylabel(r"$dR_{eq}/dt$ (px/s)")
    plt.title("Global growth-rate proxy from frame_kinetics")
    plt.legend()
    savefig(out_dir / "compare_global_dReqdt_px_per_s_vs_t_FAPI_vs_FAPI-TEMPO.png")

    # ----- physical units if available -----
    if "R_um" in g_fapi.columns and "R_um" in g_tempo.columns:
        plt.figure(figsize=(10, 6))
        plt.plot(g_fapi["t_ms"], g_fapi["R_um"], label="FAPI")
        plt.plot(g_tempo["t_ms"], g_tempo["R_um"], label="FAPI-TEMPO")
        plt.xlabel("time (ms)")
        plt.ylabel(r"Global equivalent radius $R_{eq}$ ($\mu$m)")
        plt.title("Global growth proxy (physical units)")
        plt.legend()
        savefig(out_dir / "compare_global_Req_um_vs_t_FAPI_vs_FAPI-TEMPO.png")

        plt.figure(figsize=(10, 6))
        plt.plot(g_fapi["t_ms"], g_fapi["dRdt_um_per_s"], label="FAPI")
        plt.plot(g_tempo["t_ms"], g_tempo["dRdt_um_per_s"], label="FAPI-TEMPO")
        plt.xlabel("time (ms)")
        plt.ylabel(r"$dR_{eq}/dt$ ($\mu$m/s)")
        plt.title("Global growth-rate proxy (physical units)")
        plt.legend()
        savefig(out_dir / "compare_global_dReqdt_um_per_s_vs_t_FAPI_vs_FAPI-TEMPO.png")


# ============================================================
# Main
# ============================================================

def main():
    mkdir_p(OUT_DIR)

    print("[INFO] Loading compare curves...")
    rate_fapi = load_rate_curve(COMPARE_OUT_DIR / "rate_curve_FAPI.csv", "FAPI")
    rate_tempo = load_rate_curve(COMPARE_OUT_DIR / "rate_curve_FAPI-TEMPO.csv", "FAPI-TEMPO")
    nt_fapi = load_Nt_curve(COMPARE_OUT_DIR / "Nt_curve_FAPI.csv", "FAPI")
    nt_tempo = load_Nt_curve(COMPARE_OUT_DIR / "Nt_curve_FAPI-TEMPO.csv", "FAPI-TEMPO")

    print("[INFO] Loading event files...")
    fapi_events_path = FAPI_MATCHED_DIR / "kinetics_tau0p3_events_FAPI.csv"
    tempo_events_path = TEMPO_STABLE_DIR / "kinetics_tau0p3_events.csv"
    print(f"  FAPI events path       : {fapi_events_path}")
    print(f"  FAPI-TEMPO events path : {tempo_events_path}")
    events_fapi = load_events_csv(fapi_events_path, "FAPI")
    events_tempo = load_events_csv(tempo_events_path, "FAPI-TEMPO")

    print("[INFO] Loading growth data (best-effort)...")
    g_fapi = load_global_frame_growth(FAPI_FRAME_KIN_CSV, "FAPI")
    g_tempo = load_global_frame_growth(TEMPO_FRAME_KIN_CSV, "FAPI-TEMPO")

    # Save growth proxy tables if present
    if g_fapi is not None:
        g_fapi.to_csv(OUT_DIR / "global_growth_proxy_FAPI.csv", index=False)
    if g_tempo is not None:
        g_tempo.to_csv(OUT_DIR / "global_growth_proxy_FAPI-TEMPO.csv", index=False)

    # Main figures
    plot_dn_dt(rate_fapi, rate_tempo, OUT_DIR)
    plot_Nt(nt_fapi, nt_tempo, OUT_DIR)
    plot_Nt_normalized(nt_fapi, nt_tempo, OUT_DIR)
    plot_event_hist(events_fapi, events_tempo, OUT_DIR, EVENT_HIST_BIN_MS)
    plot_event_hist_rate(events_fapi, events_tempo, OUT_DIR, EVENT_HIST_BIN_MS)
    plot_tau_robustness_panel(COMPARE_OUT_DIR, OUT_DIR)
    plot_growth_proxy(g_fapi, g_tempo, OUT_DIR)

    # Summary metrics
    summary_rows = []
    for name, nt_df, rate_df, ev_df, g_df in [
        ("FAPI", nt_fapi, rate_fapi, events_fapi, g_fapi),
        ("FAPI-TEMPO", nt_tempo, rate_tempo, events_tempo, g_tempo),
    ]:
        row = {"dataset": name}
        row.update(summarize_dataset(nt_df, rate_df, ev_df, g_df))
        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(OUT_DIR / "compare_summary_plus_growth_metrics_FAPI_vs_FAPI-TEMPO.csv", index=False)

    # Input manifest
    manifest = pd.DataFrame([
        {"key": "COMPARE_OUT_DIR", "value": str(COMPARE_OUT_DIR)},
        {"key": "FAPI_MATCHED_DIR", "value": str(FAPI_MATCHED_DIR)},
        {"key": "TEMPO_STABLE_DIR", "value": str(TEMPO_STABLE_DIR)},
        {"key": "FAPI_FRAME_KIN_CSV", "value": str(FAPI_FRAME_KIN_CSV)},
        {"key": "TEMPO_FRAME_KIN_CSV", "value": str(TEMPO_FRAME_KIN_CSV)},
        {"key": "PX_TO_UM", "value": "" if PX_TO_UM is None else str(PX_TO_UM)},
        {"key": "EVENT_HIST_BIN_MS", "value": str(EVENT_HIST_BIN_MS)},
    ])
    manifest.to_csv(OUT_DIR / "final_panels_input_manifest.csv", index=False)

    print("[OK] Final panel outputs written to:")
    print(f"  {OUT_DIR}")
    print("[OK] Generated figures:")
    print("  - compare_dn_dt_FAPI_vs_FAPI-TEMPO.png")
    print("  - compare_Nt_FAPI_vs_FAPI-TEMPO.png")
    print("  - compare_Nt_normalized_FAPI_vs_FAPI-TEMPO.png")
    print("  - compare_event_hist_FAPI_vs_FAPI-TEMPO.png")
    print("  - compare_event_hist_rate_FAPI_vs_FAPI-TEMPO.png")
    print("  - tau_robustness_panel_FAPI_fixed_vs_TEMPO_tau_sweep.png (if tau sweep files exist)")
    if g_fapi is not None and g_tempo is not None:
        print("  - compare_global_Req_px_vs_t_FAPI_vs_FAPI-TEMPO.png")
        print("  - compare_global_dReqdt_px_per_s_vs_t_FAPI_vs_FAPI-TEMPO.png")
        if PX_TO_UM is not None:
            print("  - compare_global_Req_um_vs_t_FAPI_vs_FAPI-TEMPO.png")
            print("  - compare_global_dReqdt_um_per_s_vs_t_FAPI_vs_FAPI-TEMPO.png")
    else:
        print("  - (growth figures skipped; missing/insufficient frame_kinetics inputs)")


if __name__ == "__main__":
    main()